language: c
os: osx

install:
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install nasm
  wget https://github.com/sofferjacob/edison-toolchain/releases/download/1.0.0/sierra_toolchain_mac_v.1.0.0.zip
  unzip -a sierra_toolchain_mac_v.1.0.0.zip
  export PATH=$PATH:$HOME/opt/cross/bin

script:
  make clean all floppy
